# Generated by Django 5.0.2 on 2024-05-16 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, upload_to='media')),
                ('Localisation', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Contactinfo', models.CharField(max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, upload_to='media')),
                ('Texte', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, upload_to='media')),
                ('Stage_type', models.IntegerField(choices=[(1, 'Ouvrier'), (2, 'Technicien'), (3, 'Projet de Fin dÉtudes')])),
                ('Société', models.CharField(max_length=200)),
                ('Durée', models.IntegerField()),
                ('Sujet', models.CharField(max_length=200)),
                ('Contactinfo', models.CharField(max_length=200)),
                ('Spécialité', models.CharField(max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, upload_to='media')),
                ('Départ', models.CharField(max_length=200)),
                ('Destination', models.CharField(max_length=200)),
                ('Heure_dep', models.TimeField()),
                ('Nbre_sièges', models.IntegerField()),
                ('Contactinfo', models.CharField(max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ÉvenClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, upload_to='media')),
                ('Club', models.CharField(max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ÉvenSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, upload_to='media')),
                ('Prix', models.FloatField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
