# Generated by Django 5.0.2 on 2024-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_évenclub_contactinfo_évenclub_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='évenclub',
            name='ContactInfo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='évensocial',
            name='ContactInfo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
