# Generated by Django 5.0.3 on 2024-05-19 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_remove_comment_content_type_remove_comment_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.stage'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
